title: <font size="18">Core Francisco Park</font>
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am graduate student in Physics at Harvard Unversity. I mainly focus on astrophysics and astro-staticstics.
  <br><br>
  <a href = "mailto: corefranciscopark@g.harvard.edu">Send Email:</a>
  corefranciscopark@g.harvard.edu
  <br /> 
  <a href = "mailto: cfpark00@gmail.com">Send Email:</a>
  cfpark00@gmail.com
  <br><br>
  <a href="https://www.facebook.com/corefranciscopark" target="_blank">View My Facebook Profile</a> 
  
theme: jekyll-theme-minimal
markdown: CommonMarkGhPages
